import { SymptomCategory, type OTCProduct } from "./types";

export const OTC_CATALOG: OTCProduct[] = [
  {
    id: "acetaminophen",
    name: "Tylenol Extra Strength",
    genericName: "Acetaminophen 500mg",
    categories: [SymptomCategory.HEADACHE, SymptomCategory.COLD_FLU, SymptomCategory.PAIN],
    dosageAdult: "2 caplets every 6 hours as needed. Max 6 caplets in 24 hours.",
    dosageChild: "Age 6-11: 1 caplet every 6 hours. Max 4 in 24 hours.",
    warnings: [
      "Do not exceed recommended dose",
      "Severe liver damage may occur if taking more than directed",
      "Do not use with other acetaminophen-containing products",
    ],
    contraindications: ["liver_disease", "heavy_alcohol_use"],
    drugInteractions: ["warfarin", "carbamazepine"],
    allergens: [],
    minAge: 6,
    pregnancySafe: true,
  },
  {
    id: "ibuprofen",
    name: "Advil",
    genericName: "Ibuprofen 200mg",
    categories: [SymptomCategory.HEADACHE, SymptomCategory.PAIN, SymptomCategory.COLD_FLU],
    dosageAdult: "1-2 tablets every 4-6 hours as needed. Max 3 tablets in 24 hours.",
    dosageChild: "Age 6-11: 1 tablet every 6-8 hours. Max 3 in 24 hours.",
    warnings: [
      "May cause stomach bleeding",
      "Take with food or milk",
      "Increased cardiovascular risk with prolonged use",
    ],
    contraindications: ["stomach_ulcer", "kidney_disease", "heart_disease", "aspirin_allergy"],
    drugInteractions: ["aspirin", "warfarin", "ACE_inhibitors", "lithium"],
    allergens: ["nsaid"],
    minAge: 6,
    pregnancySafe: false,
  },
  {
    id: "naproxen",
    name: "Aleve",
    genericName: "Naproxen Sodium 220mg",
    categories: [SymptomCategory.HEADACHE, SymptomCategory.PAIN],
    dosageAdult: "1 tablet every 8-12 hours. Max 2 tablets in 24 hours for OTC use.",
    warnings: [
      "May cause stomach bleeding",
      "Take with food",
      "Do not use if allergic to aspirin or other NSAIDs",
    ],
    contraindications: ["stomach_ulcer", "kidney_disease", "heart_disease", "aspirin_allergy"],
    drugInteractions: ["aspirin", "warfarin", "ACE_inhibitors", "lithium"],
    allergens: ["nsaid"],
    minAge: 12,
    pregnancySafe: false,
  },
  {
    id: "diphenhydramine",
    name: "Benadryl",
    genericName: "Diphenhydramine 25mg",
    categories: [SymptomCategory.ALLERGY, SymptomCategory.SKIN],
    dosageAdult: "1-2 tablets every 4-6 hours. Max 6 tablets in 24 hours.",
    dosageChild: "Age 6-11: 1 tablet every 4-6 hours. Max 3 in 24 hours.",
    warnings: [
      "May cause marked drowsiness",
      "Avoid alcohol",
      "Do not drive or operate machinery",
    ],
    contraindications: ["glaucoma", "enlarged_prostate", "asthma"],
    drugInteractions: ["sedatives", "MAO_inhibitors", "alcohol"],
    allergens: [],
    minAge: 6,
    pregnancySafe: false,
  },
  {
    id: "loratadine",
    name: "Claritin",
    genericName: "Loratadine 10mg",
    categories: [SymptomCategory.ALLERGY],
    dosageAdult: "1 tablet once daily. Do not take more than 1 tablet in 24 hours.",
    dosageChild: "Age 6-11: 1 children's chewable once daily.",
    warnings: [
      "Do not take more than directed",
    ],
    contraindications: ["kidney_disease", "liver_disease"],
    drugInteractions: ["ketoconazole", "erythromycin"],
    allergens: [],
    minAge: 6,
    pregnancySafe: false,
  },
  {
    id: "cetirizine",
    name: "Zyrtec",
    genericName: "Cetirizine 10mg",
    categories: [SymptomCategory.ALLERGY],
    dosageAdult: "1 tablet once daily. Do not take more than 1 tablet in 24 hours.",
    dosageChild: "Age 6-11: 1 chewable tablet (5mg) once or twice daily.",
    warnings: [
      "May cause drowsiness",
      "Avoid alcohol",
    ],
    contraindications: ["kidney_disease"],
    drugInteractions: ["sedatives", "alcohol"],
    allergens: [],
    minAge: 6,
    pregnancySafe: false,
  },
  {
    id: "guaifenesin_dxm",
    name: "Mucinex DM",
    genericName: "Guaifenesin 600mg / Dextromethorphan 30mg",
    categories: [SymptomCategory.COLD_FLU],
    dosageAdult: "1 tablet every 12 hours. Max 2 tablets in 24 hours.",
    warnings: [
      "Do not crush or chew",
      "Drink plenty of water",
      "Do not use with other cough/cold medications",
    ],
    contraindications: ["chronic_cough", "asthma"],
    drugInteractions: ["MAO_inhibitors", "SSRIs"],
    allergens: [],
    minAge: 12,
    pregnancySafe: false,
  },
  {
    id: "pseudoephedrine",
    name: "Sudafed",
    genericName: "Pseudoephedrine 30mg",
    categories: [SymptomCategory.COLD_FLU, SymptomCategory.ALLERGY],
    dosageAdult: "2 tablets every 4-6 hours. Max 8 tablets in 24 hours.",
    warnings: [
      "May cause insomnia or nervousness",
      "Ask pharmacist if you have high blood pressure",
    ],
    contraindications: ["high_blood_pressure", "heart_disease", "thyroid_disease", "diabetes"],
    drugInteractions: ["MAO_inhibitors", "beta_blockers"],
    allergens: [],
    minAge: 12,
    pregnancySafe: false,
  },
  {
    id: "omeprazole",
    name: "Prilosec OTC",
    genericName: "Omeprazole 20mg",
    categories: [SymptomCategory.DIGESTIVE],
    dosageAdult: "1 tablet once daily for 14 days. May repeat after 4 months.",
    warnings: [
      "Not for immediate heartburn relief",
      "Takes 1-4 days for full effect",
      "Do not use for more than 14 days unless directed",
    ],
    contraindications: ["liver_disease"],
    drugInteractions: ["clopidogrel", "methotrexate", "warfarin"],
    allergens: [],
    minAge: 18,
    pregnancySafe: false,
  },
  {
    id: "calcium_carbonate",
    name: "Tums",
    genericName: "Calcium Carbonate 750mg",
    categories: [SymptomCategory.DIGESTIVE],
    dosageAdult: "2-4 tablets as needed. Max 10 tablets in 24 hours.",
    dosageChild: "Age 6-11: 1-2 tablets as needed.",
    warnings: [
      "Do not take for more than 2 weeks unless directed",
    ],
    contraindications: ["kidney_disease", "hypercalcemia"],
    drugInteractions: ["tetracycline", "iron_supplements"],
    allergens: [],
    minAge: 6,
    pregnancySafe: true,
  },
  {
    id: "loperamide",
    name: "Imodium",
    genericName: "Loperamide 2mg",
    categories: [SymptomCategory.DIGESTIVE],
    dosageAdult: "2 caplets initially, then 1 after each loose stool. Max 4 caplets in 24 hours.",
    warnings: [
      "Do not use if you have bloody diarrhea",
      "Do not use for more than 2 days unless directed",
    ],
    contraindications: ["fever_with_diarrhea", "bloody_stool"],
    drugInteractions: ["ritonavir"],
    allergens: [],
    minAge: 12,
    pregnancySafe: false,
  },
  {
    id: "bismuth_subsalicylate",
    name: "Pepto-Bismol",
    genericName: "Bismuth Subsalicylate 262mg",
    categories: [SymptomCategory.DIGESTIVE],
    dosageAdult: "2 tablets every 30-60 minutes as needed. Max 8 doses in 24 hours.",
    warnings: [
      "May cause temporary darkening of stool and tongue",
      "Contains salicylate — do not use with aspirin",
    ],
    contraindications: ["aspirin_allergy", "stomach_ulcer"],
    drugInteractions: ["aspirin", "warfarin", "methotrexate"],
    allergens: ["salicylate"],
    minAge: 12,
    pregnancySafe: false,
  },
  {
    id: "hydrocortisone_cream",
    name: "Cortizone-10",
    genericName: "Hydrocortisone 1% Cream",
    categories: [SymptomCategory.SKIN, SymptomCategory.ALLERGY],
    dosageAdult: "Apply thin layer to affected area 1-4 times daily.",
    dosageChild: "Age 2+: Apply thin layer 1-3 times daily.",
    warnings: [
      "For external use only",
      "Do not use on face unless directed",
      "Do not use for more than 7 days unless directed",
    ],
    contraindications: [],
    drugInteractions: [],
    allergens: [],
    minAge: 2,
    pregnancySafe: false,
  },
  {
    id: "bacitracin",
    name: "Neosporin",
    genericName: "Bacitracin / Neomycin / Polymyxin B",
    categories: [SymptomCategory.SKIN],
    dosageAdult: "Clean wound, apply small amount 1-3 times daily. Cover with bandage.",
    dosageChild: "Same as adult dosage.",
    warnings: [
      "For external use only",
      "Stop use if rash or irritation develops",
    ],
    contraindications: [],
    drugInteractions: [],
    allergens: ["neomycin"],
    minAge: 2,
    pregnancySafe: true,
  },
  {
    id: "aloe_vera_gel",
    name: "Banana Boat Aloe Vera Gel",
    genericName: "Aloe Vera Gel",
    categories: [SymptomCategory.SKIN],
    dosageAdult: "Apply generously to affected area as needed.",
    dosageChild: "Same as adult.",
    warnings: [
      "For external use only",
      "Avoid contact with eyes",
    ],
    contraindications: [],
    drugInteractions: [],
    allergens: [],
    minAge: 0,
    pregnancySafe: true,
  },
];

export function getProductsByCategory(category: SymptomCategory): OTCProduct[] {
  return OTC_CATALOG.filter((p) => p.categories.includes(category));
}
