import { SymptomCategory, type SymptomCategoryInfo } from "./types";

export const SYMPTOM_CATALOG: SymptomCategoryInfo[] = [
  {
    id: SymptomCategory.HEADACHE,
    label: "Headache",
    icon: "Brain",
    description: "Head pain, migraines, tension headaches",
    subSymptoms: [
      { id: "tension_headache", label: "Tension / stress headache" },
      { id: "throbbing_pain", label: "Throbbing or pulsating pain" },
      { id: "sinus_pressure", label: "Sinus pressure / congestion" },
      { id: "light_sensitivity", label: "Sensitivity to light" },
      { id: "neck_stiffness", label: "Neck stiffness", isRedFlag: true },
      { id: "worst_headache_ever", label: "Worst headache of my life", isRedFlag: true },
      { id: "sudden_severe", label: "Sudden severe onset", isRedFlag: true },
      { id: "with_confusion", label: "Confusion or vision changes", isRedFlag: true },
    ],
  },
  {
    id: SymptomCategory.COLD_FLU,
    label: "Cold & Flu",
    icon: "Thermometer",
    description: "Cough, congestion, sore throat, fever",
    subSymptoms: [
      { id: "runny_nose", label: "Runny or stuffy nose" },
      { id: "sore_throat", label: "Sore throat" },
      { id: "cough_dry", label: "Dry cough" },
      { id: "cough_wet", label: "Productive cough (with mucus)" },
      { id: "mild_fever", label: "Mild fever (under 101°F / 38.3°C)" },
      { id: "body_aches", label: "Body aches and fatigue" },
      { id: "sneezing", label: "Sneezing" },
      { id: "high_fever", label: "High fever (over 103°F / 39.4°C)", isRedFlag: true },
      { id: "difficulty_breathing", label: "Difficulty breathing", isRedFlag: true },
      { id: "chest_pain", label: "Chest pain", isRedFlag: true },
    ],
  },
  {
    id: SymptomCategory.ALLERGY,
    label: "Allergies",
    icon: "Flower2",
    description: "Seasonal allergies, hay fever, mild reactions",
    subSymptoms: [
      { id: "itchy_eyes", label: "Itchy, watery eyes" },
      { id: "sneezing_allergy", label: "Frequent sneezing" },
      { id: "nasal_congestion", label: "Nasal congestion" },
      { id: "mild_skin_rash", label: "Mild skin rash or hives" },
      { id: "postnasal_drip", label: "Postnasal drip" },
      { id: "throat_swelling", label: "Throat swelling", isRedFlag: true },
      { id: "difficulty_swallowing", label: "Difficulty swallowing", isRedFlag: true },
      { id: "anaphylaxis_signs", label: "Dizziness, rapid heartbeat, faintness", isRedFlag: true },
    ],
  },
  {
    id: SymptomCategory.DIGESTIVE,
    label: "Digestive",
    icon: "Apple",
    description: "Stomach pain, heartburn, nausea, diarrhea",
    subSymptoms: [
      { id: "heartburn", label: "Heartburn / acid reflux" },
      { id: "indigestion", label: "Indigestion / bloating" },
      { id: "mild_nausea", label: "Mild nausea" },
      { id: "diarrhea", label: "Diarrhea" },
      { id: "constipation", label: "Constipation" },
      { id: "gas", label: "Gas / flatulence" },
      { id: "severe_abdominal", label: "Severe abdominal pain", isRedFlag: true },
      { id: "blood_in_stool", label: "Blood in stool", isRedFlag: true },
      { id: "persistent_vomiting", label: "Persistent vomiting", isRedFlag: true },
    ],
  },
  {
    id: SymptomCategory.PAIN,
    label: "Pain & Muscle",
    icon: "Bone",
    description: "Back pain, muscle aches, joint pain, sprains",
    subSymptoms: [
      { id: "back_pain", label: "Back pain" },
      { id: "muscle_soreness", label: "Muscle soreness / strain" },
      { id: "joint_pain", label: "Joint pain or stiffness" },
      { id: "menstrual_cramps", label: "Menstrual cramps" },
      { id: "minor_sprain", label: "Minor sprain or strain" },
      { id: "toothache", label: "Toothache" },
      { id: "chest_tightness", label: "Chest pain or tightness", isRedFlag: true },
      { id: "pain_with_numbness", label: "Pain with numbness or tingling", isRedFlag: true },
      { id: "pain_after_injury", label: "Severe pain after injury", isRedFlag: true },
    ],
  },
  {
    id: SymptomCategory.SKIN,
    label: "Skin & First Aid",
    icon: "Hand",
    description: "Minor cuts, insect bites, rashes, sunburn",
    subSymptoms: [
      { id: "minor_cut", label: "Minor cut or scrape" },
      { id: "insect_bite", label: "Insect bite / sting" },
      { id: "mild_rash", label: "Mild rash or irritation" },
      { id: "sunburn", label: "Sunburn" },
      { id: "dry_skin", label: "Dry / cracked skin" },
      { id: "athletes_foot", label: "Athlete's foot / fungal" },
      { id: "deep_wound", label: "Deep or large wound", isRedFlag: true },
      { id: "spreading_rash", label: "Rapidly spreading rash", isRedFlag: true },
      { id: "infected_wound", label: "Signs of infection (pus, red streaks)", isRedFlag: true },
    ],
  },
];

export function getCategoryInfo(category: SymptomCategory): SymptomCategoryInfo {
  return SYMPTOM_CATALOG.find((c) => c.id === category)!;
}
